run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - staticcheck
    - gosec
    - gocritic
    - govet
    - ineffassign
    - unused
    - misspell
    - gofmt
    - goimports
    - revive
    - bodyclose
    - noctx
    - prealloc

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  gosec:
    severity: medium
    confidence: medium
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
